# Generated by Django 5.0 on 2025-12-24 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "생성"),
                            ("UPDATE", "수정"),
                            ("DELETE", "삭제"),
                            ("LOGIN", "로그인"),
                            ("LOGOUT", "로그아웃"),
                            ("ACCESS", "접근"),
                            ("DOWNLOAD", "다운로드"),
                        ],
                        help_text="행위",
                        max_length=20,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        help_text="대상 앱 (예: emr, ocs)", max_length=100
                    ),
                ),
                ("model_name", models.CharField(help_text="대상 모델", max_length=100)),
                (
                    "object_id",
                    models.CharField(
                        blank=True, help_text="대상 객체 ID", max_length=100, null=True
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(
                        blank=True,
                        help_text="변경 요약 (예: [이름] 홍길동 -> 김철수)",
                        null=True,
                    ),
                ),
                (
                    "previous_data",
                    models.JSONField(blank=True, help_text="변경 전 데이터", null=True),
                ),
                (
                    "current_data",
                    models.JSONField(blank=True, help_text="변경 후 데이터", null=True),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="접속 IP", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="브라우저 정보", null=True),
                ),
                ("path", models.TextField(blank=True, help_text="API 경로", null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="발생 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="활동 사용자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_logs_user_id_fbfd51_idx",
                    ),
                    models.Index(
                        fields=["app_label", "model_name"],
                        name="audit_logs_app_lab_372e98_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                ],
            },
        ),
    ]
