# Generated by Django 5.0 on 2025-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabTestMaster",
            fields=[
                (
                    "test_code",
                    models.CharField(
                        help_text="검사 코드 (LOINC/자체코드)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_name", models.CharField(help_text="검사명", max_length=255)),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        help_text="검체 유형 (예: Blood, Urine)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, help_text="검사 방법", max_length=100, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="검사 단위 (예: mg/dL, g/L)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True,
                        help_text="참고치 범위 (예: 70-110)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="사용 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "검사 마스터",
                "verbose_name_plural": "검사 마스터 목록",
                "db_table": "lis_lab_test_master",
            },
        ),
    ]
