# Generated by Django 5.0 on 2025-12-24 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0003_encounterdiagnosis"),
        ("lis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "result_id",
                    models.CharField(
                        help_text="결과 ID (예: LR-2025-000001)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_value",
                    models.CharField(
                        help_text="검사 결과값 (수치 또는 텍스트)", max_length=100
                    ),
                ),
                (
                    "result_unit",
                    models.CharField(
                        blank=True, help_text="결과 단위", max_length=50, null=True
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, help_text="이상치 여부"),
                ),
                (
                    "abnormal_flag",
                    models.CharField(
                        blank=True,
                        help_text="이상치 플래그 (H: High, L: Low, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(auto_now_add=True, help_text="보고 일시"),
                ),
                (
                    "reported_by",
                    models.CharField(help_text="보고자 user_id", max_length=36),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="연관된 처방",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="emr.order",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="환자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="emr.patientcache",
                    ),
                ),
                (
                    "test_master",
                    models.ForeignKey(
                        help_text="검사 마스터 정보",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lis.labtestmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사 결과",
                "verbose_name_plural": "검사 결과 목록",
                "db_table": "lis_lab_results",
                "ordering": ["-reported_at"],
            },
        ),
    ]
