# Generated by Django 6.0 on 2025-12-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "encounter_id",
                    models.CharField(
                        help_text="진료 ID (예: E-2025-005678)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doctor_id",
                    models.CharField(
                        help_text="의사 user_id (ACCT_USERS 외래키)", max_length=36
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "외래"),
                            ("emergency", "응급"),
                            ("inpatient", "입원"),
                            ("discharge", "퇴원"),
                        ],
                        help_text="진료 유형",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(help_text="진료 부서", max_length=100)),
                (
                    "chief_complaint",
                    models.TextField(blank=True, help_text="주 호소", null=True),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="진단", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="scheduled",
                        help_text="진료 상태",
                        max_length=20,
                    ),
                ),
                ("encounter_date", models.DateTimeField(help_text="진료 일시")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "진료 기록",
                "verbose_name_plural": "진료 기록 목록",
                "db_table": "emr_encounters",
                "ordering": ["-encounter_date"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(
                        help_text="처방 ID (예: O-2025-009876)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ordered_by",
                    models.CharField(help_text="처방 의사 user_id", max_length=36),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("medication", "약물"),
                            ("lab", "검사"),
                            ("radiology", "영상"),
                            ("procedure", "시술"),
                        ],
                        help_text="처방 유형",
                        max_length=50,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "일반"),
                            ("urgent", "긴급"),
                            ("stat", "즉시"),
                        ],
                        default="routine",
                        help_text="긴급도",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        help_text="처방 상태",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="처방 메모", null=True),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(auto_now_add=True, help_text="처방 시간"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, help_text="실행 시간", null=True),
                ),
                (
                    "executed_by",
                    models.CharField(
                        blank=True, help_text="실행자 user_id", max_length=36, null=True
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_column="encounter_id",
                        help_text="진료 기록",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="emr.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방",
                "verbose_name_plural": "처방 목록",
                "db_table": "ocs_orders",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "item_id",
                    models.CharField(
                        help_text="처방 항목 ID (예: OI-001)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "drug_code",
                    models.CharField(
                        blank=True, help_text="약물 코드", max_length=50, null=True
                    ),
                ),
                ("drug_name", models.CharField(help_text="약물명", max_length=200)),
                ("dosage", models.CharField(help_text="용량 (예: 1정)", max_length=50)),
                (
                    "frequency",
                    models.CharField(help_text="횟수 (예: 1일 1회)", max_length=50),
                ),
                (
                    "duration",
                    models.CharField(help_text="기간 (예: 7일)", max_length=20),
                ),
                (
                    "route",
                    models.CharField(help_text="투여 경로 (예: 경구)", max_length=50),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="복용 지시사항", null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        help_text="처방",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="emr.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방 항목",
                "verbose_name_plural": "처방 항목 목록",
                "db_table": "ocs_order_items",
            },
        ),
        migrations.CreateModel(
            name="PatientCache",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        help_text="환자 ID (예: P-2024-001234)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("family_name", models.CharField(help_text="성", max_length=50)),
                ("given_name", models.CharField(help_text="이름", max_length=50)),
                ("birth_date", models.DateField(help_text="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "남성"),
                            ("female", "여성"),
                            ("other", "기타"),
                            ("unknown", "미상"),
                        ],
                        help_text="성별",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="전화번호", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="이메일", max_length=100, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="주소", null=True)),
                (
                    "emergency_contact",
                    models.JSONField(
                        blank=True,
                        help_text="응급 연락처 정보 {'name': '...', 'relationship': '...', 'phone': '...'}",
                        null=True,
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        help_text="알레르기 목록 ['페니실린', '땅콩']",
                        null=True,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        help_text="혈액형 (예: A+, B-, O+, AB-)",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "openemr_patient_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenEMR의 환자 ID (FHIR Patient resource ID)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="OpenEMR과 마지막 동기화 시간", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 시간"),
                ),
            ],
            options={
                "verbose_name": "환자 캐시",
                "verbose_name_plural": "환자 캐시 목록",
                "db_table": "emr_patient_cache",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family_name", "given_name"], name="idx_patient_name"
                    ),
                    models.Index(fields=["birth_date"], name="idx_patient_birth"),
                    models.Index(fields=["phone"], name="idx_patient_phone"),
                ],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                help_text="환자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="emr.patientcache",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                help_text="환자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="emr.patientcache",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["patient", "ordered_at"], name="idx_patient_order"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["ordered_by", "ordered_at"], name="idx_doctor_order"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="idx_order_status"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_type"], name="idx_order_type"),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "encounter_date"], name="idx_patient_encounter"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["doctor_id", "encounter_date"], name="idx_doctor_encounter"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["status"], name="idx_encounter_status"),
        ),
    ]
