# Generated by Django 5.0 on 2025-12-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="version",
            field=models.IntegerField(
                default=1, help_text="낙관적 락을 위한 버전 필드"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="version",
            field=models.IntegerField(
                default=1, help_text="낙관적 락을 위한 버전 필드"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="version",
            field=models.IntegerField(
                default=1, help_text="낙관적 락을 위한 버전 필드"
            ),
        ),
        migrations.AddField(
            model_name="patientcache",
            name="version",
            field=models.IntegerField(
                default=1, help_text="낙관적 락을 위한 버전 필드"
            ),
        ),
    ]
