# Generated by Django 5.0 on 2025-12-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0002_encounter_version_order_version_orderitem_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diag_code",
                    models.CharField(help_text="질병 코드 (ICD-10/KCD)", max_length=20),
                ),
                (
                    "diagnosis_name",
                    models.CharField(help_text="진단명 (한글/영문)", max_length=255),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="진단 우선순위 (1: 주진단, 2 이상: 부진단)"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        help_text="진료 기록",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="emr.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "진료 진단",
                "verbose_name_plural": "진료 진단 목록",
                "db_table": "emr_encounter_diagnoses",
                "ordering": ["priority", "created_at"],
            },
        ),
    ]
