# Generated by Django 5.0 on 2025-12-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0003_encounterdiagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounterdiagnosis",
            name="comments",
            field=models.TextField(
                blank=True, help_text="진단 상세 설명/메모", null=True
            ),
        ),
    ]
