# Generated by Django 5.0 on 2025-12-22 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("study_id", models.UUIDField(help_text="RadiologyStudy FK")),
                (
                    "model_type",
                    models.CharField(
                        help_text="AI 모델 종류 (e.g., tumor_detection)", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, help_text="AI 분석 결과", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="실패 시 에러 메시지"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True, help_text="RabbitMQ 큐 추가 시간", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["study_id"], name="ai_aijob_study_i_175663_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_aijob_status_2512af_idx",
                    ),
                ],
            },
        ),
    ]
