# Generated by Django 5.0 on 2025-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosisMaster",
            fields=[
                (
                    "diag_code",
                    models.CharField(
                        help_text="질병 코드 (ICD-10/KCD)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(help_text="질병명 (한글)", max_length=255),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, help_text="질병명 (영문)", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="분류 (대분류)", max_length=100, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="사용 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "진단 마스터",
                "verbose_name_plural": "진단 마스터 목록",
                "db_table": "ocs_diagnosis_master",
            },
        ),
        migrations.CreateModel(
            name="MedicationMaster",
            fields=[
                (
                    "drug_code",
                    models.CharField(
                        help_text="약물 표준 코드 (KDC/EDI)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "drug_name",
                    models.CharField(help_text="약물명 (상품명)", max_length=255),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True,
                        help_text="성분명 (일반명)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        blank=True,
                        help_text="제형 (예: 정제, 주사제)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        help_text="함량 (예: 500mg)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="단위 (예: 정, 바이알)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="제조사/수입사", max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="사용 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "약물 마스터",
                "verbose_name_plural": "약물 마스터 목록",
                "db_table": "ocs_medication_master",
            },
        ),
    ]
