# Generated by Django 5.0 on 2025-12-22 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyOrder",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(help_text="OpenEMR patient ID", max_length=100),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CT", "CT"),
                            ("MRI", "MRI"),
                            ("XR", "X-Ray"),
                            ("US", "Ultrasound"),
                            ("NM", "Nuclear Medicine"),
                        ],
                        max_length=10,
                    ),
                ),
                ("body_part", models.CharField(max_length=100)),
                (
                    "clinical_info",
                    models.TextField(blank=True, help_text="임상 정보 및 검사 목적"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ORDERED",
                        max_length=20,
                    ),
                ),
                ("priority", models.CharField(default="ROUTINE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ordered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiology_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyStudy",
            fields=[
                (
                    "study_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "orthanc_study_id",
                    models.CharField(
                        help_text="Orthanc 내부 Study ID", max_length=100, unique=True
                    ),
                ),
                (
                    "study_instance_uid",
                    models.CharField(
                        help_text="DICOM StudyInstanceUID", max_length=255, unique=True
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_id", models.CharField(max_length=100)),
                ("study_date", models.DateField(blank=True, null=True)),
                ("study_time", models.TimeField(blank=True, null=True)),
                ("study_description", models.TextField(blank=True)),
                ("modality", models.CharField(blank=True, max_length=10)),
                ("referring_physician", models.CharField(blank=True, max_length=200)),
                ("num_series", models.IntegerField(default=0)),
                ("num_instances", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Orthanc와 마지막 동기화 시간"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studies",
                        to="ris.radiologyorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-study_date", "-study_time"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("findings", models.TextField(help_text="판독 소견")),
                ("impression", models.TextField(help_text="판독 결론")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "radiologist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="ris.radiologystudy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="radiologyorder",
            index=models.Index(
                fields=["patient_id", "created_at"],
                name="ris_radiolo_patient_6b9ab3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologyorder",
            index=models.Index(fields=["status"], name="ris_radiolo_status_566094_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologystudy",
            index=models.Index(
                fields=["patient_id", "study_date"],
                name="ris_radiolo_patient_00d651_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologystudy",
            index=models.Index(
                fields=["orthanc_study_id"], name="ris_radiolo_orthanc_3d167a_idx"
            ),
        ),
    ]
